### ISSUE TITLE
Failed to provision hikvision DS-2CD2143G0-I

### ISSUE THREAD

**Issue by hotake77** [aws-quickstart/quickstart-onica-connected-camera#8] opened 2019-03-25 15:06 UTC
Tried to provision a Hikvision DS-2CD2143G0-I which should be supported.
But I get the following error.

<img width="299" alt="スクリーンショット 2019-03-25 23 38 12" src="https://user-images.githubusercontent.com/48918522/54928392-2b606f00-4f57-11e9-910d-811963b8bc40.png">

I have the camera fully configured validated through mobile app and the camera is up and operating. 
I discover my camera with Config  App.but Failed to provision.

- enviroment
Model : DS-2CD2143G0-I
Firmware version : V5.5.82 build 181211

Best regards.

**Comment by presmini** [comment] 2019-04-26 00:07
I am also encountering this problem. 
Model: DS-2CD2025FWD-I
Firmware version: V5.5.0 build 170725

Did you find a solution to the issue?

Thanks!
Paolo

**Comment by macbutch** [comment] 2019-05-02 07:54
I see the same:

* Model: DS-2CD2343G0-I
* Firmware: V5.5.61 build 180718

These cameras should work but afaict the provisioning API doesn't exist on mine at all.

**Comment by shitijkarsolia** [comment] 2019-05-03 09:45
![errorIoT](https://user-images.githubusercontent.com/36421373/57130143-3d36fc80-6db6-11e9-950f-96699788578f.png)


I am also encountering the exact same problem.
Model: HIKVISION DS-2CD1410F-IW

Did anyone find a solution to the issue?

**Comment by rbeckonica** [comment] 2019-05-06 17:34
Assuming you've tried both http and https scheme, I can confirm this issue indicates the camera does not have the expected provisioning API. You may need support from the camera vendor.

**Comment by shitijkarsolia** [comment] 2019-05-08 09:16
> Assuming you've tried both http and https scheme, I can confirm this issue indicates the camera does not have the expected provisioning API. You may need support from the camera vendor.

Since my current IP Camera is not working, I am planning to purchase a new camera that is supported by AWS IoT Camera Connector.

Could you suggest a model that works smoothly with quicksight without any issues?
Appreciate the help!

**Comment by sshvans** [comment] 2019-05-29 16:20
@shitijkarsolia The deployment guide of this Quick Start lists supported cameras. You can take a look at it here. https://aws-quickstart.s3.amazonaws.com/quickstart-onica-connected-camera/doc/aws-iot-camera-connector-on-the-aws-cloud.pdf
Closing this PR for now. Feel free to reopen if you encounter an issue again.

**Closed by sshvans** 2019-05-29 16:20 UTC
